version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    networks:
      - banking-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - banking-net

  liquibase:
    image: liquibase/liquibase
    container_name: liquibase
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/banking
      LIQUIBASE_USERNAME: your_username
      LIQUIBASE_PASSWORD: your_password
      LIQUIBASE_CHANGELOG_FILE: /liquibase/changelog/changelog-master.yaml
    networks:
      - banking-net
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
networks:
  banking-net:

