version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  liquibase:
    depends_on:
      - postgres
    image: liquibase/liquibase:4.30.0
    #environment:
    #  URL: jdbc:postgresql://postgres:5432/banking
    #  USERNAME: postgres
    #  PASSWORD: password
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    entrypoint:
      - liquibase
      - --url=jdbc:postgresql://postgres:5432/banking
      - --username=postgres
      - --password=password
      - --changelog-file=/liquibase/changelog/db.changelog-master.yaml
      - update

